// Parses the backend's assembled memo markdown into renderable pieces.
// The exact heading structure ("## N. Title") is controlled by
// backend/app/memo.py's _assemble_markdown(), so this parsing is safe to
// rely on rather than fragile - both sides are maintained together.

export type MemoSection = { title: string; body: string };

export function parseMemoSections(narrative: string): MemoSection[] {
  const lines = narrative.split("\n");
  const sections: MemoSection[] = [];
  let current: { title: string; body: string[] } | null = null;

  for (const line of lines) {
    const headerMatch = line.match(/^## \d+\.\s*(.+)$/);
    if (headerMatch) {
      if (current) {
        sections.push({ title: current.title, body: current.body.join("\n").trim() });
      }
      current = { title: headerMatch[1].trim(), body: [] };
    } else if (current) {
      current.body.push(line);
    }
  }
  if (current) {
    sections.push({ title: current.title, body: current.body.join("\n").trim() });
  }
  return sections;
}

export function parseMemoSubtitle(narrative: string): string | null {
  const line = narrative.split("\n").find((l) => l.trim().startsWith("*Generated by"));
  return line ? line.trim().replace(/^\*|\*$/g, "") : null;
}

export function findSection(sections: MemoSection[], title: string): string {
  return sections.find((s) => s.title === title)?.body ?? "";
}

export type ParsedTable = { headers: string[]; rows: string[][] };

export function splitFinancialAnalysis(body: string): { table: ParsedTable | null; ratiosMarkdown: string } {
  const marker = "**Ratios**";
  const markerIndex = body.indexOf(marker);
  const tablePart = markerIndex === -1 ? body : body.slice(0, markerIndex);
  const ratiosPart = markerIndex === -1 ? "" : body.slice(markerIndex + marker.length).trim();
  return { table: parseMarkdownTable(tablePart), ratiosMarkdown: ratiosPart };
}

function parseMarkdownTable(text: string): ParsedTable | null {
  const lines = text.split("\n").filter((l) => l.trim().startsWith("|"));
  if (lines.length < 2) {
    return null;
  }
  const parseRow = (line: string) =>
    line
      .trim()
      .replace(/^\||\|$/g, "")
      .split("|")
      .map((cell) => cell.trim());
  const headers = parseRow(lines[0]);
  const rows = lines.slice(2).map(parseRow); // row 1 is the "---|---|---" separator
  return { headers, rows };
}

// "-$11,817 million" (backend's plain-minus notation) -> "($11,817 million)"
// (accounting style, for the document table only - prose keeps the phrasing as generated).
export function toAccountingStyle(value: string): string {
  const match = value.match(/^-(\$[\d,]+(?:\.\d+)?\s*\w*)$/);
  return match ? `(${match[1]})` : value;
}
